services:
  marqo-custom:
    build:
      context: scripts/.
      dockerfile: Dockerfile
    ports:
      - "8882:8882"
  front:
    build:
      context: frontend/
      dockerfile: Dockerfile
    depends_on: 
      - marqo-custom
    healthcheck:
      test: "[[ $(curl --fail http://localhost:8882/indexes | grep -ic 'writeups') -eq 1 ]] || exit 1"
      interval: 5s
      retries: 10
      start_period: 20s
      timeout: 10s
    ports:
      - "4173:4173"
